insert into countries (name, code, flag_url) values
  ('Afghanistan', 'af', 'https://flagcdn.com/w320/af.png'),
  ('Albania', 'al', 'https://flagcdn.com/w320/al.png'),
  ('Algeria', 'dz', 'https://flagcdn.com/w320/dz.png'),
  ('Andorra', 'ad', 'https://flagcdn.com/w320/ad.png'),
  ('Angola', 'ao', 'https://flagcdn.com/w320/ao.png'),
  ('Antigua and Barbuda', 'ag', 'https://flagcdn.com/w320/ag.png'),
  ('Argentina', 'ar', 'https://flagcdn.com/w320/ar.png'),
  ('Armenia', 'am', 'https://flagcdn.com/w320/am.png'),
  ('Australia', 'au', 'https://flagcdn.com/w320/au.png'),
  ('Austria', 'at', 'https://flagcdn.com/w320/at.png'),
  ('Azerbaijan', 'az', 'https://flagcdn.com/w320/az.png'),
  ('Bahamas', 'bs', 'https://flagcdn.com/w320/bs.png'),
  ('Bahrain', 'bh', 'https://flagcdn.com/w320/bh.png'),
  ('Bangladesh', 'bd', 'https://flagcdn.com/w320/bd.png'),
  ('Barbados', 'bb', 'https://flagcdn.com/w320/bb.png'),
  ('Belarus', 'by', 'https://flagcdn.com/w320/by.png'),
  ('Belgium', 'be', 'https://flagcdn.com/w320/be.png'),
  ('Belize', 'bz', 'https://flagcdn.com/w320/bz.png'),
  ('Benin', 'bj', 'https://flagcdn.com/w320/bj.png'),
  ('Bhutan', 'bt', 'https://flagcdn.com/w320/bt.png'),
  ('Bolivia', 'bo', 'https://flagcdn.com/w320/bo.png'),
  ('Bosnia and Herzegovina', 'ba', 'https://flagcdn.com/w320/ba.png'),
  ('Botswana', 'bw', 'https://flagcdn.com/w320/bw.png'),
  ('Brazil', 'br', 'https://flagcdn.com/w320/br.png'),
  ('Brunei', 'bn', 'https://flagcdn.com/w320/bn.png'),
  ('Bulgaria', 'bg', 'https://flagcdn.com/w320/bg.png'),
  ('Burkina Faso', 'bf', 'https://flagcdn.com/w320/bf.png'),
  ('Burundi', 'bi', 'https://flagcdn.com/w320/bi.png'),
  ('Cabo Verde', 'cv', 'https://flagcdn.com/w320/cv.png'),
  ('Cambodia', 'kh', 'https://flagcdn.com/w320/kh.png'),
  ('Cameroon', 'cm', 'https://flagcdn.com/w320/cm.png'),
  ('Canada', 'ca', 'https://flagcdn.com/w320/ca.png'),
  ('Central African Republic', 'cf', 'https://flagcdn.com/w320/cf.png'),
  ('Chad', 'td', 'https://flagcdn.com/w320/td.png'),
  ('Chile', 'cl', 'https://flagcdn.com/w320/cl.png'),
  ('China', 'cn', 'https://flagcdn.com/w320/cn.png'),
  ('Colombia', 'co', 'https://flagcdn.com/w320/co.png'),
  ('Comoros', 'km', 'https://flagcdn.com/w320/km.png'),
  ('Congo', 'cg', 'https://flagcdn.com/w320/cg.png'),
  ('Costa Rica', 'cr', 'https://flagcdn.com/w320/cr.png'),
  ('Croatia', 'hr', 'https://flagcdn.com/w320/hr.png'),
  ('Cuba', 'cu', 'https://flagcdn.com/w320/cu.png'),
  ('Cyprus', 'cy', 'https://flagcdn.com/w320/cy.png'),
  ('Czech Republic', 'cz', 'https://flagcdn.com/w320/cz.png'),
  ('DR Congo', 'cd', 'https://flagcdn.com/w320/cd.png'),
  ('Denmark', 'dk', 'https://flagcdn.com/w320/dk.png'),
  ('Djibouti', 'dj', 'https://flagcdn.com/w320/dj.png'),
  ('Dominica', 'dm', 'https://flagcdn.com/w320/dm.png'),
  ('Dominican Republic', 'do', 'https://flagcdn.com/w320/do.png'),
  ('Ecuador', 'ec', 'https://flagcdn.com/w320/ec.png'),
  ('Egypt', 'eg', 'https://flagcdn.com/w320/eg.png'),
  ('El Salvador', 'sv', 'https://flagcdn.com/w320/sv.png'),
  ('Equatorial Guinea', 'gq', 'https://flagcdn.com/w320/gq.png'),
  ('Eritrea', 'er', 'https://flagcdn.com/w320/er.png'),
  ('Estonia', 'ee', 'https://flagcdn.com/w320/ee.png'),
  ('Eswatini', 'sz', 'https://flagcdn.com/w320/sz.png'),
  ('Ethiopia', 'et', 'https://flagcdn.com/w320/et.png'),
  ('Fiji', 'fj', 'https://flagcdn.com/w320/fj.png'),
  ('Finland', 'fi', 'https://flagcdn.com/w320/fi.png'),
  ('France', 'fr', 'https://flagcdn.com/w320/fr.png'),
  ('Gabon', 'ga', 'https://flagcdn.com/w320/ga.png'),
  ('Gambia', 'gm', 'https://flagcdn.com/w320/gm.png'),
  ('Georgia', 'ge', 'https://flagcdn.com/w320/ge.png'),
  ('Germany', 'de', 'https://flagcdn.com/w320/de.png'),
  ('Ghana', 'gh', 'https://flagcdn.com/w320/gh.png'),
  ('Greece', 'gr', 'https://flagcdn.com/w320/gr.png'),
  ('Grenada', 'gd', 'https://flagcdn.com/w320/gd.png'),
  ('Guatemala', 'gt', 'https://flagcdn.com/w320/gt.png'),
  ('Guinea', 'gn', 'https://flagcdn.com/w320/gn.png'),
  ('Guinea-Bissau', 'gw', 'https://flagcdn.com/w320/gw.png'),
  ('Guyana', 'gy', 'https://flagcdn.com/w320/gy.png'),
  ('Haiti', 'ht', 'https://flagcdn.com/w320/ht.png'),
  ('Honduras', 'hn', 'https://flagcdn.com/w320/hn.png'),
  ('Hungary', 'hu', 'https://flagcdn.com/w320/hu.png'),
  ('Iceland', 'is', 'https://flagcdn.com/w320/is.png'),
  ('India', 'in', 'https://flagcdn.com/w320/in.png'),
  ('Indonesia', 'id', 'https://flagcdn.com/w320/id.png'),
  ('Iran', 'ir', 'https://flagcdn.com/w320/ir.png'),
  ('Iraq', 'iq', 'https://flagcdn.com/w320/iq.png'),
  ('Ireland', 'ie', 'https://flagcdn.com/w320/ie.png'),
  ('Israel', 'il', 'https://flagcdn.com/w320/il.png'),
  ('Italy', 'it', 'https://flagcdn.com/w320/it.png'),
  ('Jamaica', 'jm', 'https://flagcdn.com/w320/jm.png'),
  ('Japan', 'jp', 'https://flagcdn.com/w320/jp.png'),
  ('Jordan', 'jo', 'https://flagcdn.com/w320/jo.png'),
  ('Kazakhstan', 'kz', 'https://flagcdn.com/w320/kz.png'),
  ('Kenya', 'ke', 'https://flagcdn.com/w320/ke.png'),
  ('Kiribati', 'ki', 'https://flagcdn.com/w320/ki.png'),
  ('Kuwait', 'kw', 'https://flagcdn.com/w320/kw.png'),
  ('Kyrgyzstan', 'kg', 'https://flagcdn.com/w320/kg.png'),
  ('Laos', 'la', 'https://flagcdn.com/w320/la.png'),
  ('Latvia', 'lv', 'https://flagcdn.com/w320/lv.png'),
  ('Lebanon', 'lb', 'https://flagcdn.com/w320/lb.png'),
  ('Lesotho', 'ls', 'https://flagcdn.com/w320/ls.png'),
  ('Liberia', 'lr', 'https://flagcdn.com/w320/lr.png'),
  ('Libya', 'ly', 'https://flagcdn.com/w320/ly.png'),
  ('Liechtenstein', 'li', 'https://flagcdn.com/w320/li.png'),
  ('Lithuania', 'lt', 'https://flagcdn.com/w320/lt.png'),
  ('Luxembourg', 'lu', 'https://flagcdn.com/w320/lu.png'),
  ('Madagascar', 'mg', 'https://flagcdn.com/w320/mg.png'),
  ('Malawi', 'mw', 'https://flagcdn.com/w320/mw.png'),
  ('Malaysia', 'my', 'https://flagcdn.com/w320/my.png'),
  ('Maldives', 'mv', 'https://flagcdn.com/w320/mv.png'),
  ('Mali', 'ml', 'https://flagcdn.com/w320/ml.png'),
  ('Malta', 'mt', 'https://flagcdn.com/w320/mt.png'),
  ('Marshall Islands', 'mh', 'https://flagcdn.com/w320/mh.png'),
  ('Mauritania', 'mr', 'https://flagcdn.com/w320/mr.png'),
  ('Mauritius', 'mu', 'https://flagcdn.com/w320/mu.png'),
  ('Mexico', 'mx', 'https://flagcdn.com/w320/mx.png'),
  ('Micronesia', 'fm', 'https://flagcdn.com/w320/fm.png'),
  ('Moldova', 'md', 'https://flagcdn.com/w320/md.png'),
  ('Monaco', 'mc', 'https://flagcdn.com/w320/mc.png'),
  ('Mongolia', 'mn', 'https://flagcdn.com/w320/mn.png'),
  ('Montenegro', 'me', 'https://flagcdn.com/w320/me.png'),
  ('Morocco', 'ma', 'https://flagcdn.com/w320/ma.png'),
  ('Mozambique', 'mz', 'https://flagcdn.com/w320/mz.png'),
  ('Myanmar', 'mm', 'https://flagcdn.com/w320/mm.png'),
  ('Namibia', 'na', 'https://flagcdn.com/w320/na.png'),
  ('Nauru', 'nr', 'https://flagcdn.com/w320/nr.png'),
  ('Nepal', 'np', 'https://flagcdn.com/w320/np.png'),
  ('Netherlands', 'nl', 'https://flagcdn.com/w320/nl.png'),
  ('New Zealand', 'nz', 'https://flagcdn.com/w320/nz.png'),
  ('Nicaragua', 'ni', 'https://flagcdn.com/w320/ni.png'),
  ('Niger', 'ne', 'https://flagcdn.com/w320/ne.png'),
  ('Nigeria', 'ng', 'https://flagcdn.com/w320/ng.png'),
  ('North Korea', 'kp', 'https://flagcdn.com/w320/kp.png'),
  ('North Macedonia', 'mk', 'https://flagcdn.com/w320/mk.png'),
  ('Norway', 'no', 'https://flagcdn.com/w320/no.png'),
  ('Oman', 'om', 'https://flagcdn.com/w320/om.png'),
  ('Pakistan', 'pk', 'https://flagcdn.com/w320/pk.png'),
  ('Palau', 'pw', 'https://flagcdn.com/w320/pw.png'),
  ('Palestine', 'ps', 'https://flagcdn.com/w320/ps.png'),
  ('Panama', 'pa', 'https://flagcdn.com/w320/pa.png'),
  ('Papua New Guinea', 'pg', 'https://flagcdn.com/w320/pg.png'),
  ('Paraguay', 'py', 'https://flagcdn.com/w320/py.png'),
  ('Peru', 'pe', 'https://flagcdn.com/w320/pe.png'),
  ('Philippines', 'ph', 'https://flagcdn.com/w320/ph.png'),
  ('Poland', 'pl', 'https://flagcdn.com/w320/pl.png'),
  ('Portugal', 'pt', 'https://flagcdn.com/w320/pt.png'),
  ('Qatar', 'qa', 'https://flagcdn.com/w320/qa.png'),
  ('Romania', 'ro', 'https://flagcdn.com/w320/ro.png'),
  ('Russia', 'ru', 'https://flagcdn.com/w320/ru.png'),
  ('Rwanda', 'rw', 'https://flagcdn.com/w320/rw.png'),
  ('Saint Kitts and Nevis', 'kn', 'https://flagcdn.com/w320/kn.png'),
  ('Saint Lucia', 'lc', 'https://flagcdn.com/w320/lc.png'),
  ('Saint Vincent and the Grenadines', 'vc', 'https://flagcdn.com/w320/vc.png'),
  ('Samoa', 'ws', 'https://flagcdn.com/w320/ws.png'),
  ('San Marino', 'sm', 'https://flagcdn.com/w320/sm.png'),
  ('Sao Tome and Principe', 'st', 'https://flagcdn.com/w320/st.png'),
  ('Saudi Arabia', 'sa', 'https://flagcdn.com/w320/sa.png'),
  ('Senegal', 'sn', 'https://flagcdn.com/w320/sn.png'),
  ('Serbia', 'rs', 'https://flagcdn.com/w320/rs.png'),
  ('Seychelles', 'sc', 'https://flagcdn.com/w320/sc.png'),
  ('Sierra Leone', 'sl', 'https://flagcdn.com/w320/sl.png'),
  ('Singapore', 'sg', 'https://flagcdn.com/w320/sg.png'),
  ('Slovakia', 'sk', 'https://flagcdn.com/w320/sk.png'),
  ('Slovenia', 'si', 'https://flagcdn.com/w320/si.png'),
  ('Solomon Islands', 'sb', 'https://flagcdn.com/w320/sb.png'),
  ('Somalia', 'so', 'https://flagcdn.com/w320/so.png'),
  ('South Africa', 'za', 'https://flagcdn.com/w320/za.png'),
  ('South Korea', 'kr', 'https://flagcdn.com/w320/kr.png'),
  ('South Sudan', 'ss', 'https://flagcdn.com/w320/ss.png'),
  ('Spain', 'es', 'https://flagcdn.com/w320/es.png'),
  ('Sri Lanka', 'lk', 'https://flagcdn.com/w320/lk.png'),
  ('Sudan', 'sd', 'https://flagcdn.com/w320/sd.png'),
  ('Suriname', 'sr', 'https://flagcdn.com/w320/sr.png'),
  ('Sweden', 'se', 'https://flagcdn.com/w320/se.png'),
  ('Switzerland', 'ch', 'https://flagcdn.com/w320/ch.png'),
  ('Syria', 'sy', 'https://flagcdn.com/w320/sy.png'),
  ('Taiwan', 'tw', 'https://flagcdn.com/w320/tw.png'),
  ('Tajikistan', 'tj', 'https://flagcdn.com/w320/tj.png'),
  ('Tanzania', 'tz', 'https://flagcdn.com/w320/tz.png'),
  ('Thailand', 'th', 'https://flagcdn.com/w320/th.png'),
  ('Timor-Leste', 'tl', 'https://flagcdn.com/w320/tl.png'),
  ('Togo', 'tg', 'https://flagcdn.com/w320/tg.png'),
  ('Tonga', 'to', 'https://flagcdn.com/w320/to.png'),
  ('Trinidad and Tobago', 'tt', 'https://flagcdn.com/w320/tt.png'),
  ('Tunisia', 'tn', 'https://flagcdn.com/w320/tn.png'),
  ('Turkey', 'tr', 'https://flagcdn.com/w320/tr.png'),
  ('Turkmenistan', 'tm', 'https://flagcdn.com/w320/tm.png'),
  ('Tuvalu', 'tv', 'https://flagcdn.com/w320/tv.png'),
  ('Uganda', 'ug', 'https://flagcdn.com/w320/ug.png'),
  ('Ukraine', 'ua', 'https://flagcdn.com/w320/ua.png'),
  ('United Arab Emirates', 'ae', 'https://flagcdn.com/w320/ae.png'),
  ('United Kingdom', 'gb', 'https://flagcdn.com/w320/gb.png'),
  ('United States', 'us', 'https://flagcdn.com/w320/us.png'),
  ('Uruguay', 'uy', 'https://flagcdn.com/w320/uy.png'),
  ('Uzbekistan', 'uz', 'https://flagcdn.com/w320/uz.png'),
  ('Vanuatu', 'vu', 'https://flagcdn.com/w320/vu.png'),
  ('Vatican City', 'va', 'https://flagcdn.com/w320/va.png'),
  ('Venezuela', 've', 'https://flagcdn.com/w320/ve.png'),
  ('Vietnam', 'vn', 'https://flagcdn.com/w320/vn.png'),
  ('Yemen', 'ye', 'https://flagcdn.com/w320/ye.png'),
  ('Zambia', 'zm', 'https://flagcdn.com/w320/zm.png'),
  ('Zimbabwe', 'zw', 'https://flagcdn.com/w320/zw.png')
on conflict (code) do nothing;
